### ISSUE TITLE
[Feature request] Show current layer/layer count

### ISSUE THREAD

**Issue by jonsag** [tpmullan/OctoPrint-DetailedProgress#31] opened 2021-01-16 22:56 UTC
Hi

For me a good addition to the output on the display is to also show current layer/layer count,
ie something like 'Layer 123/456'.

Or perhaps this is already possible and I've missed it?

Anyway, thanks for this great plugin
/jon

**Comment by tpmullan** [comment] 2021-01-19 23:15
Currently we have
```
    # Messages to display. Placeholders:
    # - completion : The % completed
    # - printTime : A string in the format "HH:MM:SS" with how long the print is going
    # - printTimeLeft : A string in the format "HH:MM:SS" with how long the print still has left
    # - ETA : The date and time formatted in "%H:%M:%S Day %d" that the print is estimated to be completed
    # - filepos: The current position in the file currently being printed
    # - filename: The filename of file currently being printed
    # - accuracy: Accuracy of the time estimates
```

So this would be a new feature.  I currently do not have time to implement this, but would happily accept a pull request.

**Comment by jonsag** [comment] 2021-01-19 23:19
No problems.

I'll look into it.

/jon

**Comment by tpmullan** [comment] 2021-01-19 23:46
It also looks like this might be a duplicate of #14 and there are some examples of projects that use the variable that you want.

And this is where you would add your layer variable to the message.
https://github.com/tpmullan/OctoPrint-DetailedProgress/blob/master/octoprint_detailedprogress/__init__.py#L136
```python
		return message.format(
			completion=currentData["progress"]["completion"],
			printTime=currentData["progress"]["printTimeString"],
			printTimeLeft=currentData["progress"]["printTimeLeftString"],
			ETA=currentData["progress"]["ETA"],
			filepos=currentData["progress"]["filepos"],
			accuracy=currentData["progress"]["accuracy"],
			filename=currentData["progress"]["filename"]
		)
```

We are currently getting the state data from https://github.com/tpmullan/OctoPrint-DetailedProgress/blob/master/octoprint_detailedprogress/__init__.py#L68 which is provided by https://docs.octoprint.org/en/master/modules/printer.html#

Good luck 👍

**Comment by jonsag** [comment] 2021-01-21 23:04
Added a pull request, #32

**Comment by jonsag** [comment] 2021-01-23 19:36
I've also added some code to #32  , since there was more info available in DisplayProgess events, in. Sorry for messing a bit with some unnecessary commits...
/jon

**Comment by tpmullan** [comment] 2021-01-25 15:10
Close by merging #32

**Closed by tpmullan** 2021-01-25 15:10 UTC
Labels: enhancement, help wanted
